### ISSUE TITLE
ICS20: support base denoms with slashes

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc#737]
ibc-go [now supports base denoms with slashes](https://github.com/cosmos/ibc-go/pull/978). We should probably update the standard so that other implementations can also support [chains that require it](https://github.com/cosmos/ibc-go/issues/894).

ibc-rs is planning on supporting base denoms with slashes as well ([PR](https://github.com/informalsystems/ibc-rs/pull/1989)).

**Comment by crodriguezvega** [comment]
Thanks for opening this issue, @plafer.

When I opened the PR to add the support for base denoms with slashes, I thought that it was a bug on ibc-go that base denoms were not supported, since they are valid denoms for the Cosmos SDK. But back then I didn't realize (re-reading the spec now) that the [spec said](https://github.com/cosmos/ibc/blob/master/spec/app/ics-020-fungible-token-transfer/README.md#data-structures):

```
If {denom} contains /, then it must also be in the ics20 form which indicates that this token has a multi-hop record. Note that this requires that the / (slash character) is prohibited in non-IBC token denomination names.
```

So does the above means that ibc-go should not have added support for slashes in base denoms? Looks like we should have agreed on a spec change first before implementing the support in the implementation...

**Comment by ethanfrey** [comment]
@sunnya96
@valardragon
 this may be relevant to the token factory osmosis inplemented

**Comment by colin-axner** [comment]
I think this is only an issue if the chain implementing ics20 stores the received denominations using the full path (ie it doesn't differetiate between a minted token with the denom `{ics20Port}/{ics20Channel}/{denom}` and a IBC token received with the denom `{ics20Port}/{ics20Channel}/{denom}`). Since ibc-go uses the `ibc/{hash}` representation for internal tracking, a newly minted token in the form `{ics20Port}/{ics20Channel}/{denom}` will be treated differently than the actual token received via IBC with that same path

If my assumption is correct, I'd be in favor of changing the spec to indicate this. I think it also might be useful to recommend the `ibc/{hash}` approach as best practice, but maybe there are good reasons not to do this?

cc @AdityaSripal
